= Contributing

In the spirit of free software, _everyone_ is encouraged to help improve this project.

To contribute code, simply fork the project on GitHub, hack away and send a pull request with your proposed changes.
Feel free to use the https://github.com/asciidoctor/atom-autocomplete-asciidoc/issues[issue tracker] to provide feedback or suggestions in other ways.

== Project organization

The project is hosted and run using GitHub.
The issue tracker is in place to report bugs, discuss improvements, show our ambitious goals and desires for the future, and encourage each other.
Classification labels and versioning tags are added for clarity and the ability to search.

=== Labels

Labels are added to issues and pull request for clarity, in the present but also when looking back at previous issues and pull requests.

.Type labels
|===
|bug         | the current implementation has a flaw that needs to be resolved
|question    | generic question
|improvement | refinement on top of an existing feature
|enhancement | new feature
|duplicate   | a similar (open) issue already exists
|invalid     | not reproducible or out of date
|declined    | a decision was made not to pursue
|===

.Category labels
|===
|snippets       | included snippets to reduce the amount of typing
|completions    | included completions to reduce the amount of typing
|===

.Status labels
|===
|WIP   | currently a Work In Progress, not ready for a merge
|ready | development is done
|===

== Development

=== Retrieve the source code

The source code for this plugin is available from https://github.com/asciidoctor/atom-autocomplete-asciidoc

=== Retrieve the dependencies

Use the following command to download dependencies (https://github.com/atom/season[Season], http://www.coffeelint.org/[CoffeeLint], ...):

[source, shell]
----
apm install
----

=== Prepare for business

. Decide what you want to work on, and what should be the result
. Have a GitHub account
. Fork the project to your personal account
. Check out your forked project for local development using git
. Navigate to the directory using the command line interface
. Link the package using `apm link -d`, and start atom in dev-mode using the command `atom -d .`
. _Develop_ (this is where the magic happens)
. Commit and push your code onto your forked project
. Make a pull request and fill in the pull request template to request for the changes to be merged into the upstream project
. Answer questions or make adjustments based on the discussion around the pull request
. Wait for the merge, wait for the next release, use it in your normal Atom install
. _Show off to others what you have made, and feel proud for you have improved the lives of many by contributing to this package!_

== Quality assurance

When opening a pull request on GitHub, https://travis-ci.org/asciidoctor/atom-autocomplete-asciidoc[Travis CI] will run the Atom package specs and lint using CoffeeScript files.
Of course you can do so yourself, so you can ensure your code will pass the check in the pull-request.

=== CoffeeScript lint

This package uses http://www.coffeelint.org/[CoffeeLint] to ensure that the code is uniformly structured.
The linter definitions are defined in the link:coffeelint.json[coffeelint.json].

When developing in Atom, the https://atom.io/packages/linter-coffeelint[linter-coffeelint] package exposes the linting in your editor.
It does require CoffeeLint to be http://www.coffeelint.org/#install[installed].

CoffeeLint can also be triggered from the command line:

[source, shell]
----
coffeelint -f coffeelint.json lib/*.coffee spec/*-spec.coffee
----

=== Package specs

Tests are defined in link:spec/[spec directory], which provide snippets of text and test if the parsed result meet the expectations.
Ideally all grammar features are covered in the specs (100% test coverage), with both positive and negative tests.
Having these tests present will help future contributors make improvements without accidentally breaking other parts of the package.

There are multiple ways in which you can run the tests:

.Testing from the command line
[source, shell]
----
atom -t spec
----

.Testing via the Command Pallet in Atom
----
Window: Run Package Specs
----

.Testing using the build-package.sh script
[source, shell]
----
curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh > build-package.sh
sh build-package.sh
----

.Testing syntax
* http://flight-manual.atom.io/hacking-atom/sections/writing-specs[Atom specs]
* http://jasmine.github.io/1.3/introduction.html[Jasmine 1.3]

== Compat mode not supported

This package implements the modern AsciiDoc syntax endorsed by Asciidoctor.
It does not support the legacy AsciiDoc syntax permitted by Asciidoctor with http://asciidoctor.org/docs/migration/#compat-mode[compat mode] enabled or by AsciiDoc Python.

The reason compat mode is not supported is two-fold.

. An Atom grammar is not capable of supporting different modes based on a setting within the document.
. Since this project is part of the Asciidoctor organization, which endorses a modern, consistent AsciiDoc syntax, this package is aimed at encouraging migration away from the legacy syntax.

We hope this package encourages authors to write good, clean, modern AsciiDoc.

== Snippets

Snippets are defined in link:snippets/language-asciidoc.cson[snippets/language-asciidoc.cson].

== Package publising

We use https://travis-ci.org[Travis CI] to publish this package.

Every merged PR is released as a new version (by default a `patch`).

We use the https://travis-ci.org/asciidoctor/atom-language-asciidoc/settings[Travis CI UI] to manage the publishing system via secure environment variables:

* `PUBLISH_TYPE`: default `patch`, can be change to `minor`, `major`.
* `STOP_PUBLISH`: if defined, prevent the publishing.
* `$encrypted_xxxx_key` and `$encrypted_xxxx_iv`: defined the main key and vector to encrypt the SSH key.
* `ATOM_ACCESS_TOKEN`: defined the Atom token for `apm`.
